//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubSync.GUI.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubSync.GUI.Localization.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is running!.
        /// </summary>
        internal static string AppRunning {
            get {
                return ResourceManager.GetString("AppRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start {0}.
        /// </summary>
        internal static string AppStart {
            get {
                return ResourceManager.GetString("AppStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        internal static string AppStarting {
            get {
                return ResourceManager.GetString("AppStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop {0}.
        /// </summary>
        internal static string AppStop {
            get {
                return ResourceManager.GetString("AppStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} stopped!.
        /// </summary>
        internal static string AppStopped {
            get {
                return ResourceManager.GetString("AppStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping....
        /// </summary>
        internal static string AppStopping {
            get {
                return ResourceManager.GetString("AppStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \r\n\r\n(Please keep the following information)\r\n\r\nApp Version: {0}\r\nOS Version: {1} {2}\r\n.NET runtime: {3}.
        /// </summary>
        internal static string ContactUsEmailBody {
            get {
                return ResourceManager.GetString("ContactUsEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo design by {0}.
        /// </summary>
        internal static string DesignBy {
            get {
                return ResourceManager.GetString("DesignBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed with lots of love by {0}.
        /// </summary>
        internal static string DevelopedBy {
            get {
                return ResourceManager.GetString("DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder was already selected.
        /// </summary>
        internal static string DirectoryAlreadySelected {
            get {
                return ResourceManager.GetString("DirectoryAlreadySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the program to apply the language changes.
        /// </summary>
        internal static string LanguageChangeRestart {
            get {
                return ResourceManager.GetString("LanguageChangeRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Start {0}....
        /// </summary>
        internal static string MenuAppStart {
            get {
                return ResourceManager.GetString("MenuAppStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Stop {0}....
        /// </summary>
        internal static string MenuAppStop {
            get {
                return ResourceManager.GetString("MenuAppStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available!.
        /// </summary>
        internal static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} available for download!\n\nPress OK to visit the website and download the new version.
        /// </summary>
        internal static string NewVersionAvailableDescription {
            get {
                return ResourceManager.GetString("NewVersionAvailableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got any bug to report or some gold bars to donate? {0}!.
        /// </summary>
        internal static string ReportBugs {
            get {
                return ResourceManager.GetString("ReportBugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle downloaded for {0}.
        /// </summary>
        internal static string SubtitleDownloaded {
            get {
                return ResourceManager.GetString("SubtitleDownloaded", resourceCulture);
            }
        }
    }
}
